#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# 智能工作区配置
$config/configs/workspace-setup.sh &

flclash &
dunst &
fcitx5 &
foot --server &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/.config/backgrounds/cat-rainbow-arch.png &
# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
