#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# FlClash &
dunst &
pot &
fcitx5 &
foot --server &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/.config/backgrounds/awesome.png &
# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
