windowrulev2=size 1920x1080,class:^(Minecraft).*$
windowrulev2=size 1920x1080,class:^(DOOM).*$
windowrulev2=float,class:,title:^(Picture in picture)$
windowrulev2=pin,class:,title:^(Picture in picture)$
windowrulev2=float,class:^(TransAI)$
windowrulev2=size 800 600,title:^(TransAI)$
